---
- hosts: servers
  
  vars_files:
      - ./vars_file.yml
      
  tasks:
    - name: Print Debug message.
      debug:
        msg: "Hi from Ansible"

    - name: install nginx and vim
      apt: name=nginx,vim state=present
