---
- hosts: servers

  vars_files:
      - ./vars_file.yml
      
  tasks:
    - name: Print Vars from file.
      debug:
        msg: "{{varFromFile3}}"
      tags: tag1

    - name: Print Var1 and Var2
      debug:
        msg: "Var1 value is {{varFromFile1}} and Var3 value is {{varFromFile3}}"
      tags: tag2

